<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,17,1,'55S15b2x');
$cfg_Cs[2]=array(1,17,1,'54ix5oOF');
$cfg_Cs[3]=array(1,17,1,'5Ymn5oOF');
$cfg_Cs[4]=array(1,17,1,'5Zac5Ymn');
$cfg_Cs[5]=array(1,17,1,'5Yqo5L2c');
$cfg_Cs[6]=array(1,17,1,'54G+6Zq+');
$cfg_Cs[7]=array(1,17,1,'5p6q5oiY');
$cfg_Cs[8]=array(1,17,1,'5aWH5bm7');
$cfg_Cs[9]=array(0,18,1,'55S16KeG5Ymn');
$cfg_Cs[10]=array(9,18,1,'5YaF5Zyw');
$cfg_Cs[11]=array(9,18,1,'5riv5Y+w');
$cfg_Cs[12]=array(9,18,1,'5qyn576O');
$cfg_Cs[13]=array(9,18,1,'5pel6Z+p');
?>