<field:language itemname="语言" autofield="1" notsend="0" type="checkbox" isnull="true" islist="0" default="国语,欧美,日韩"  maxlength="250" page="">
</field:language>
<field:score itemname="评分分值" autofield="1" notsend="0" type="float" isnull="true" islist="0" default="0.0"  maxlength="250" page="">
</field:score>
<field:people_num itemname="评分人数" autofield="1" notsend="0" type="int" isnull="true" islist="0" default="0"  maxlength="250" page="">
</field:people_num>
<field:area itemname="地区" autofield="1" notsend="0" type="radio" isnull="true" islist="0" default="大陆,欧美,港台"  maxlength="250" page="">
</field:area>
<field:years itemname="年代" autofield="1" notsend="0" type="select" isnull="true" islist="0" default="2017,2016,2015,更早"  maxlength="250" page="">
</field:years>
<field:director itemname="导演" autofield="1" notsend="0" type="multitext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:director>
<field:actors itemname="主演" autofield="1" notsend="0" type="multitext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:actors>
<field:introduce itemname="剧情介绍" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:introduce>
