<?php
$z[0]=Array("global","",12,37);
$z[0][4]['name']="autoindex";
$z[1]=Array("arcurl","",48,63);
$z[2]=Array("litpic","",92,107);
$z[3]=Array("title","",114,128);
$z[4]=Array("language","",159,176);
$z[5]=Array("arcurl","",192,207);
$z[6]=Array("title","",225,239);
$z[7]=Array("score","",243,287);
$z[7][4]['function']="getSmallStars(@me)";
$z[8]=Array("score","@me=round(@me,2);",291,348);
$z[8][4]['runphp']="yes";

?>